version: "2.2"
services:
  overworld:
    image: "dstacademy/dontstarvetogether:0.7"
    command: dst-server start --update=all
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${SERVICE_OVERWORLD_PORT:-10999}:${SERVICE_OVERWORLD_PORT:-10999}/udp"
    env_file:
      - ./env/world.env
      - ./env/overworld.env
      - ./.env
    environment:
      - SERVER_PORT=${SERVICE_OVERWORLD_PORT:-10999}
    cpuset: ${MACHINE_CPUS}
  underworld:
    image: "dstacademy/dontstarvetogether:0.7"
    command: dst-server start --update=all
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${SERVICE_UNDERWORLD_PORT:-11000}:${SERVICE_UNDERWORLD_PORT:-11000}/udp"
    env_file:
      - ./env/world.env
      - ./env/underworld.env
      - ./.env
    environment:
      - SERVER_PORT=${SERVICE_UNDERWORLD_PORT:-11000}
    cpuset: ${MACHINE_CPUS}
  log:
    image: "dstacademy/filebeat:0.2"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data/filebeat.yml:/filebeat.yml
    volumes_from:
      - overworld:ro
    extra_hosts:
      - "buffer:${BUFFER_ADDRESS}"
    env_file:
      - ./env/log.env
      - ./.env
    cpuset: ${MACHINE_CPUS}
