version: "2"
services:
  overworld:
    image: "dstacademy/dontstarvetogether:0.7"
    command: dst-server start --update=all
    container_name: overworld
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "10999:10999/udp"
    env_file:
      - ./env/world.env
      - ./env/overworld.env
      - ./.env
  underworld:
    image: "dstacademy/dontstarvetogether:0.7"
    command: dst-server start --update=all
    container_name: underworld
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "11000:11000/udp"
    env_file:
      - ./env/world.env
      - ./env/underworld.env
      - ./.env
  log:
    image: "dstacademy/filebeat:0.2"
    container_name: log
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data/filebeat.yml:/filebeat.yml
    extra_hosts:
      - "buffer:${BUFFER_ADDRESS}"
    env_file:
      - ./env/log.env
      - ./.env
