version: "3.6"
services:
  overworld:
    image: dstacademy/dontstarvetogether:0.8
    command: dst-server start --update=all
    restart: always
    ports:
      - "${SERVICE_OVERWORLD_PORT:-10999}:${SERVICE_OVERWORLD_PORT:-10999}/udp"
    volumes:
      - ./state:/var/lib/dsta/cluster
    env_file:
      - ./env/world.env
      - ./env/overworld.env
      - ./.env
    environment:
      - SERVER_PORT=${SERVICE_OVERWORLD_PORT:-10999}
  underworld:
    image: dstacademy/dontstarvetogether:0.8
    command: dst-server start --update=all
    restart: always
    ports:
      - "${SERVICE_UNDERWORLD_PORT:-11000}:${SERVICE_UNDERWORLD_PORT:-11000}/udp"
    volumes:
      - ./state:/var/lib/dsta/cluster
    env_file:
      - ./env/world.env
      - ./env/underworld.env
      - ./.env
    environment:
      - SERVER_PORT=${SERVICE_UNDERWORLD_PORT:-11000}
  heal:
    image: "willfarrell/autoheal"
    environment:
      - AUTOHEAL_CONTAINER_LABEL=academy.dst.config.update
      - AUTOHEAL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
